### ISSUE TITLE
Rebuilding option list leaves me with an additional dropdown

### ISSUE THREAD

**Issue by jrichview** [israel-munoz/multiselect-dropdown#1]
I'm using your script for a dropdown whose options are set programatically based on a user's selection within another control. So, the user selects the type of list they want to see, then some script code rebuilds the list of options in the multi-select list. 

Unfortunately, when this happens, it creates a whole new dropdown. Examining the dom I'm thinking it looks like there are 2 nested controls.

![capture2](https://user-images.githubusercontent.com/2236908/48027682-71877400-e117-11e8-829b-466858af2584.JPG)
![capture1](https://user-images.githubusercontent.com/2236908/48027683-71877400-e117-11e8-9a15-d05c2e820674.JPG)

From what I can tell this happens when I call "multiSelect()" a second time after updating the options. If I do not call it, then I don't get an extra select control, but I also don't get the updated list of options.

**Comment by israel-munoz** [comment]
I didn't consider that before. I just uploaded a new version with a reload function to update the list of options from the same \<select> element.
`multiSelect.reload(selectElement);`

Also in this version, calling again the multiSelect function will do the same as reload.

**Comment by jrichview** [comment]
That's fantastic, thanks. I was going to make a custom mod locally, but this is much better!
